### ISSUE TITLE
Deauth error

### ISSUE THREAD

**Issue by Illuminaris1968** [MS-WEB-BN/h4rpy#2]
Fresh install in the deauth window i put in the mac adress of my own AP's connectied client - the number of deauth packets and press return and is greeted with 

Invalid AP MAC address.
"aireplay-ng --help" for help.

I am only requested to input the client mac adress - not the AP mac adress

I assume this is the cause of the error

**Comment by Illuminaris1968** [comment]
Got it working using only my ap mac adress and not the client mac adress

**Comment by MS-WEB-BN** [comment]
@Illuminaris1968 you are not supposed to enter AP's mac adress, since "ad.sh" records it, and client mac adress is optional.
